name: GALLERY-360-ARTIST-REORGANISING-LOGIC

on:
  push:
    branches:
      - main
      - developer
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'  # Update to match the provided Node.js version

      - name: Install project dependencies
        run: npm install --legacy-peer-deps

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Patch build.gradle files
        run: |
          find . -name "build.gradle" -exec sed -i 's/useCoreDependencies()//g' {} +
          find . -name "build.gradle" -exec sed -i 's/compileSdkVersion.*/compileSdkVersion 30/g' {} +

      # Android APK Build
      - name: Build Android APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android --profile production --non-interactive --wait

      - name: Display Build Logs
        if: failure()
        run: cat /home/expo/workingdir/build/logs/EASBuildWorker.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            ./android/app/build/outputs/apk/release/app-release.apk