name: GALLERY-360-ARTIST-REORGANISING-LOGIC

on:
  push:
    branches:
      - main
      - developer
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Use a compatible Node.js version for SDK 49 and expo-cli

      - name: Install project dependencies
        run: npm install --legacy-peer-deps

      # Install Expo CLI (supports SDK 49 and expo publish)
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Install expo-updates (required for expo publish with SDK 49)
      - name: Install expo-updates
        run: npm install expo-updates

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Use expo publish for SDK 49
      - name: Publish Expo App (SDK 49)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo publish --non-interactive

      - name: Build Android APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android --non-interactive --no-wait --profile production

      # Wait for the APK build to complete
      - name: Wait for APK build to complete
        run: npx expo build:status

      # Download the APK
      - name: Download APK
        run: |
          APK_URL=$(npx expo url:apk)
          curl -o app.apk "$APK_URL"

      # Upload APK as an artifact
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-file
          path: app.apk
