name: GALLERY-360-ARTIST-REORGANISING-LOGIC

on:
  push:
    branches:
      - main
      - developer
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Compatible Node.js version for Expo SDK 49

      - name: Install project dependencies
        run: npm install --legacy-peer-deps

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install expo-updates
        run: npm install expo-updates --legacy-peer-deps

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Android APK Build using the manual command
      - name: Build Android APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android --profile production --non-interactive

      - name: Download APK
        run: |
          APK_URL=$(eas build:list --status=finished --non-interactive --json | jq -r '.[0].artifacts.buildUrl')
          if [ -z "$APK_URL" ]; then
            echo "Failed to fetch APK URL" && exit 1
          fi
          curl -o app.apk "$APK_URL"

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-file
          path: app.apk
